apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: k8s-multi-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: shuub.club
  dnsNames:
    - shuub.club
    - www.shuub.club
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - shuub.club
          - www.shuub.club